export const house_List = [
  {
    id: 1,
    name: "4-Bedroom Duplex Apartment",
    image: House6,
    rating: 3.5,
    state: "Enugu State",
    location: "Abakpa Nike",
    rent: "₦2,000,000 per Year",
    description:
      "Spacious duplex with four bedrooms, parking space, and modern interior finishes.",
    amenities: [
      { label: "Bedrooms", value: 4, icon: FaBed  },
      { label: "Bathrooms", value: 3, icon: FaBath},
      { label: "Kitchen", value: true, icon: MdKitchen},
      { label: "Parking", value: true, icon: FaCar},
      { label: "WiFi", value: true, icon: FaWifi},
      { label: "Furnished", value: true, icon: FaCouch},
      { label: "Water Supply", value: true, icon: FaWater},
    ],
  },
  {
    id: 2,
    name: "2 Bedrooms Flat",
    image: House5,
    rating: 4.7,
    state: "Rivers State",
    location: "Peter Odili RD, PH",
    rent: "₦650,000 per Year",
    description:
      "Affordable and cozy 2-bedroom flat in a peaceful neighborhood.",
    amenities: [
      { label: "Bedrooms", value: 2, icon: FaBed},
      { label: "Bathrooms", value: 2, icon: FaBath},
      { label: "Kitchen", value: true, icon: MdKitchen},
      { label: "WiFi", value: true, icon: FaWifi},
      { label: "Water Supply", value: true, icon: FaWater},
    ],
  },
  {
    id: 3,
    name: "3 Bedrooms Bungalow",
    image: House2,
    rating: 4.9,
    state: "Abuja FCT",
    location: "Gwarimpa",
    rent: "₦1,200,000 per Year",
    description:
      "Beautifully finished bungalow with spacious rooms and a small compound.",
    amenities: [
      { label: "Bedrooms", value: 3, icon: FaBed},
      { label: "Bathrooms", value: 2, icon: FaBath},
      { label: "Kitchen", value: true, icon: MdKitchen},
      { label: "Parking", value: true, icon: FaCar},
      { label: "Furnished", value: true, icon: FaCouch},
      { label: "Water Supply", value: true, icon: FaWater},
    ],
  },
  {
    id: 4,
    name: "Luxury 5-Bedroom Duplex",
    image: House3,
    rating: 4.5,
    state: "Lagos State",
    location: "Lekki Phase 1",
    rent: "₦4,500,000 per Year",
    description:
      "A luxury duplex with premium finishing, swimming pool, and 24/7 security.",
    amenities: [
      { label: "Bedrooms", value: 5, icon: FaBed},
      { label: "Bathrooms", value: 5, icon: FaBath},
      { label: "Swimming Pool", value: true, icon: FaSwimmingPool},
      { label: "Security", value: true, icon: FaShieldAlt},
      { label: "WiFi", value: true, icon: FaWifi},
      { label: "Parking", value: true, icon: FaCar},
      { label: "Furnished", value: true, icon: FaCouch},
      { label: "Water Supply", value: true, icon: FaWater},
    ],
  },
  {
    id: 5,
    name: "1 Bedroom Self Contained",
    image: House4,
    rating: 4.0,
    state: "Anambra State",
    location: "Awka",
    rent: "₦250,000 per Year",
    description:
      "Compact one-bedroom self-contained apartment suitable for students or single tenants.",
    amenities: [
      { label: "Bedrooms", value: 1, icon: FaBed},
      { label: "Bathrooms", value: 1, icon: FaBath},
      { label: "Kitchen", value: true, icon: MdKitchen},
      { label: "Water Supply", value: true, icon: FaWater},
    ],
  },
];
